package com.example.controller.searching;

import java.util.Stack;

import com.example.model.Maze;
import com.example.model.Pos2D;

/**
 * Interface for SearchAlgorithm.
 */
public interface SearchAlgorithm {

    /**
     * Returns the movestack, generated by the algorithm.
     * 
     * @return
     */
    public Stack<Pos2D> getMoveStack();

    /**
     * Searches for the goal using the algorithm.
     * 
     * @return
     */
    public Node search();

    /**
     * Sets the start position for the algorithm.
     * @param pos
     */
    public void setStart(Pos2D pos);

    /**
     * Sets the goal position for the algorithm.
     * @param pos
     */
    public void setGoal(Pos2D pos);

    /**
     * Sets the maze of the search algorithm.
     * @param maze
     */
    public void setMaze(Maze maze);
}
